### ISSUE TITLE
Kinda sad this never got released.

### ISSUE THREAD

**Issue by leycec** [michaelgale/cq-kit#1]
`cq-kit` has a ridiculous amount to offer. It'd be great if either:

* `cq-kit` could get at least **a single official PyPI-hosted release** before being officially retired. Yes, I acknowledge that PyPI is superficially useless in this case – because CadQuery itself (i.e., the main mandatory runtime dependency of `cq-kit`) is unavailable on PyPI. So, why? Conda-forge, in a word. Given a single PyPI-hosted release, releasing a **single official Anaconda release** is trivial on `conda-forge`. `</shrug>`
* The most critical subsets of `cq-kit` could be **merged upstream into the main CadQuery codebase.** Whenever free time and volunteer enthusiasm permits, <sup>*...so never is what I'm saying*</sup> would you be willing to submit one or more CadQuery PRs to that effect? Specifically:
  * [The `export_step_file()` improvements delineated here](https://github.com/michaelgale/cq-kit#file-io) seem especially germane. Those are really all unconditional improvements to CadQuery's vanilla STEP exporter. Your changeset really deserves to see a broader audience.
  * The `export_iges_file()` exporter. CadQuery currently lacks *any* IGES support whatsoever, so this would be a tremendous add. An `import_iges_file()` importer would be great as well, but... you know. Can't beg too much. Easy does it there!

Interestingly, `pythonocc-core` *also* abruptly halted development at about the same time as this project's final commit. Even more interestingly, I'm sequestered in the verdant woods of Sharbot Lake – a mere 45 minutes outside of Ottawa. I know, eh? `</ahem>`

Whichever way you elect to take this, thanks for all the community investment. You rock the CAD scene, Mike! :rocket:

**Comment by michaelgale** [comment]
Closing.  PyPI installer made and IGES file import added.

**Comment by leycec** [comment]
**Fantasmic.** Thanks so much for the jolly Christmas surprise, Mike! :christmas_tree:
